"""Service for tracking per-user translation costs."""

import datetime
import os
from typing import cast

from sqlalchemy import func
from sqlalchemy.orm import Session

from app.database import db_session
from app.models import Translation, User

# Monthly limit in dollars
MONTHLY_LIMIT_USD = 1.00

# Comma-separated list of usernames exempt from monthly budget limits
_unlimited_users_env = os.environ.get("UNLIMITED_USERS", "")
UNLIMITED_USERS = {u.strip() for u in _unlimited_users_env.split(",") if u.strip()}


def get_user_monthly_cost(user_id: int) -> float:
    """
    Calculate the total cost of translations generated by a user in the current month.
    """
    session = cast(Session, db_session)

    # Get start of current month
    now = datetime.datetime.now()
    month_start = datetime.datetime(now.year, now.month, 1)

    total_cost = (
        session.query(func.sum(Translation.cost))
        .filter(
            Translation.user_id == user_id,
            Translation.created_at >= month_start,
        )
        .scalar()
        or 0.0
    )

    return float(total_cost)


def check_user_budget(username: str) -> tuple[bool, float]:
    """
    Check if a user is within their monthly budget.

    Returns:
        tuple[bool, float]: (is_allowed, current_spend)
        - is_allowed: True if user can make more translations
        - current_spend: Current month's spending in USD
    """
    # Unlimited users bypass the check
    if username in UNLIMITED_USERS:
        return (True, 0.0)

    session = cast(Session, db_session)
    user = session.query(User).filter(User.username == username).first()

    if not user:
        return (False, 0.0)

    current_spend = get_user_monthly_cost(user.id)
    is_allowed = current_spend < MONTHLY_LIMIT_USD

    return (is_allowed, current_spend)
