services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dhivehi-translation-arena-dev
    restart: always
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8101:8101"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    command: ["uv", "run", "--no-cache", "flask", "run", "--host", "0.0.0.0", "--port", "8101"]
    networks:
      - translation-net-dev

networks:
  translation-net-dev:
    driver: bridge
