import logging
import threading
import time
from dataclasses import dataclass
from typing import ClassVar

from openrouter import OpenRouter

from app.config import ModelConfig, get_config

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class TranslationResult:
    text: str
    cost: float
    cost_source: str
    generation_id: str | None = None
    served_model: str | None = None
    provider_name: str | None = None
    service_tier: str | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    reasoning_tokens: int | None = None
    cached_tokens: int | None = None


class TranslationClient:
    """OpenRouter translation client with rate limiting and cost tracking."""

    @property
    def SYSTEM_PROMPT(self) -> str:
        return get_config().SYSTEM_PROMPT

    _shared_state: ClassVar[dict[str, dict[str, float | int]]] = {}
    _lock = threading.Lock()

    def __init__(self, model_key: str, model_config: ModelConfig) -> None:
        self.model_key = model_key
        self.model_config = model_config
        self.model_name = model_config["name"]
        self.input_cost_per_mtok = model_config["input_cost_per_mtok"]
        self.output_cost_per_mtok = model_config["output_cost_per_mtok"]
        self.rate_limit = model_config.get("rate_limit")
        self.reasoning = model_config.get("reasoning")
        self.custom_temperature = model_config.get("temperature")
        self.timeout = model_config.get("timeout", 90.0)

    def translate(self, text: str, user_id: int | None = None) -> TranslationResult:
        cfg = get_config()
        if not cfg.OPENROUTER_API_KEY:
            return TranslationResult("Error: API key not configured for OpenRouter", 0.0, "estimated")

        if not self._check_rate_limit():
            return TranslationResult(f"Error: Rate limit exceeded for model {self.model_name}. Please try again later.", 0.0, "estimated")

        try:
            client = OpenRouter(
                api_key=cfg.OPENROUTER_API_KEY,
                http_referer=cfg.OPENROUTER_HTTP_REFERER,
                x_open_router_title=cfg.OPENROUTER_APP_TITLE,
                x_open_router_categories=cfg.OPENROUTER_APP_CATEGORIES,
            )
            provider = dict(self.model_config.get("provider", {}))
            if cfg.OPENROUTER_ENFORCE_ZDR:
                provider["zdr"] = True
            completion = client.chat.send(
                model=self.model_name,
                models=self.model_config.get("fallback_models"),
                messages=[
                    {"role": "system", "content": self.SYSTEM_PROMPT},
                    {"role": "user", "content": text},
                ],
                temperature=self.custom_temperature if self.custom_temperature is not None else cfg.DEFAULT_TEMPERATURE,
                reasoning=self.reasoning,
                provider=provider or None,
                user=f"arena-user-{user_id}" if user_id is not None else None,
                timeout_ms=int(self.timeout * 1000),
            )

            logger.info("Full OpenRouter Response for %s: %r", self.model_name, completion)

            if not completion.choices:
                logger.warning("OpenRouter response for %s had no choices.", self.model_name)
                return TranslationResult("Error: No response generated by model.", 0.0, "estimated")

            choice = completion.choices[0]

            if choice.finish_reason == "length":
                error_msg = "Error: The response was cut off because it reached the maximum token limit."
                logger.warning("%s for model %s", error_msg, self.model_name)
                return TranslationResult(error_msg, 0.0, "estimated")

            translation = choice.message.content or ""

            data = completion.model_dump()
            usage = data.get("usage") or {}
            input_tokens = usage.get("prompt_tokens") or len(text) / 4
            output_tokens = usage.get("completion_tokens") or len(translation) / 4
            billed_cost = usage.get("cost")
            cost = float(billed_cost) if billed_cost is not None else self._calculate_cost(input_tokens, output_tokens)
            details = usage.get("completion_tokens_details") or {}
            prompt_details = usage.get("prompt_tokens_details") or {}
            attempts = ((data.get("openrouter_metadata") or {}).get("attempts") or [])
            provider_name = attempts[-1].get("provider") if attempts else None
            logger.info("OpenRouter translation successful for %s.", self.model_name)
            return TranslationResult(
                translation, cost, "openrouter_billed" if billed_cost is not None else "estimated",
                generation_id=data.get("id"), served_model=data.get("model"), provider_name=provider_name,
                service_tier=data.get("service_tier"), prompt_tokens=usage.get("prompt_tokens"),
                completion_tokens=usage.get("completion_tokens"), reasoning_tokens=details.get("reasoning_tokens"),
                cached_tokens=prompt_details.get("cached_tokens"),
            )

        except Exception as e:
            logger.exception("OpenRouter translation failed for %s", self.model_name)
            return TranslationResult(f"Error: {e!s}", 0.0, "estimated")

    def _calculate_cost(self, input_tokens: float, output_tokens: float) -> float:
        cost = ((input_tokens * self.input_cost_per_mtok) + (output_tokens * self.output_cost_per_mtok)) / 1_000_000
        logger.debug(
            "Cost calculation for %s: input_tokens=%s, output_tokens=%s, cost=%s",
            self.model_name,
            input_tokens,
            output_tokens,
            cost,
        )
        return cost

    def _check_rate_limit(self) -> bool:
        if not self.rate_limit:
            return True

        current_time = time.time()
        rate_limit_window = 60

        with self._lock:
            if self.model_key not in self._shared_state:
                self._shared_state[self.model_key] = {
                    "last_request_time": current_time,
                    "request_count": 1,
                }
                return True

            state = self._shared_state[self.model_key]
            last_request_time = state["last_request_time"]
            request_count = state["request_count"]

            if current_time - last_request_time < rate_limit_window:
                if request_count >= self.rate_limit:
                    return False
                state["request_count"] += 1
            else:
                state["last_request_time"] = current_time
                state["request_count"] = 1

        return True


def get_translation_client(model_key: str) -> TranslationClient:
    model_config = get_config().MODELS.get(model_key)
    if not model_config:
        msg = f"Unknown model: {model_key}"
        raise ValueError(msg)

    return TranslationClient(model_key, model_config)


def get_available_models() -> dict[str, str]:
    return {
        key: model["display_name"]
        for key, model in get_config().MODELS.items()
        if model.get("is_active", True) and not model.get("is_hidden", False)
    }
